dataset: 'force'
data_dir: '/pgeoprj/godeep/ej44/datasets/force'
logs: 
- 'GR'
- 'RHOB'
- 'NPHI'
- 'DTC'
logs_info:
- 'WELL'
- 'DEPTH_MD'
- 'GR' 
- 'RHOB'
- 'NPHI'
- 'DTC'
class_col: 'LITHOLOGY'
num_classes: 11