# array-like of shape (n_classes,), default=None. Prior probabilities of the classes. If specified, the priors are not adjusted according to the data.
priors: null

# float, default=1e-9. Portion of the largest variance of all features that is added to variances for calculation stability.
var_smoothing: 0.000000001