dataset: 'force'
data_dir: 'https://raw.githubusercontent.com/bolgebrygg/Force-2020-Machine-Learning-competition/master/lithology_competition/data/'
logs: 
- 'GR'
- 'RHOB'
- 'NPHI'
- 'DTC'
logs_info:
- 'WELL'
- 'DEPTH_MD'
- 'GR' 
- 'RHOB'
- 'NPHI'
- 'DTC'
- 'LITHOLOGY'
class_col: 'LITHOLOGY'
num_classes: 11