dataset: 'geolink'
data_dir: 'https://drive.google.com/uc?id='
logs: 
- 'GR'
- 'RHOB'
- 'NPHI'
- 'DTC'
logs_info:
- 'WELL'
- 'DEPT'
- 'GR' 
- 'RHOB'
- 'NPHI'
- 'DTC'
class_col: 'LITHOLOGY'
num_classes: 27